backend:
  name: git-gateway
  # name: test-repo
  branch: master
  # publish_mode: editorial_workflow

collections:
  - name: "article"
    label: "Article"
    folder: "src/content/blog"
    create: true
    media_folder: "src/assets/article"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summery", name: "summery", widget: "string" }
      - { label: "Thumbnail image", name: "thumbnail", widget: "file" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: "src/assets/images"
public_folder: "src/assets/images"
